{
 "title": "Kafka Connect",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Record Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Record Lag By Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Records" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_consumer_consumer_fetch_manager_metrics_records_lag{topic=~\"scalyr-.*\"})"
    }
   ]
  },
  {
   "title": "Avg Record Lag per Partition All Topics",
   "type": "graph",
   "description": "Avg record lag per partition across all topics",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Records" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_consumer_fetch_manager_metrics_records_lag{topic=~\"scalyr-.*\"})",
     "legendFormat": "Num Records"
    }
   ]
  },
  {
   "title": "Avg Record Lag per Partition By Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Records" }
   ],
   "targets": [
    {
     "expr": "avg by (topic) (kafka_consumer_consumer_fetch_manager_metrics_records_lag{topic=~\"scalyr-.*\"})"
    }
   ]
  },
  { "title": "Sink Task Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Avg Records Put/Sec per Task",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Records" }
   ],
   "targets": [
    {
     "expr": "avg by (connector) (kafka_connect_sink_task_metrics_sink_record_send_rate)"
    }
   ]
  },
  {
   "title": "Put Batch Max Time ms",
   "type": "graph",
   "description": "Maximum time in milliseconds for put call to complete",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "millisecs" }
   ],
   "targets": [
    {
     "expr": "max by (connector) (kafka_connect_sink_task_metrics_put_batch_max_time_ms)"
    }
   ]
  },
  {
   "title": "In-flight Record Count",
   "type": "graph",
   "description": "Number of records read from Kafka but not yet committed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Records" }
   ],
   "targets": [
    {
     "expr": "sum by (connector) (kafka_connect_sink_task_metrics_sink_record_active_count)"
    }
   ]
  },
  {
   "title": "Avg Num Partitions per Task",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Partitions" }
   ],
   "targets": [
    {
     "expr": "avg by (connector) (kafka_connect_sink_task_metrics_partition_count)"
    }
   ]
  },
  {
   "title": "Number of Tasks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_task_count)"
    }
   ]
  },
  {
   "title": "Task Startup Failure Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_task_startup_failure_total)"
    }
   ]
  }
 ]
}