{
 "title": "Prometheus Health",
 "description": "Overview of current Prometheus health",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Estimated 30 day Storage Requirements / GiB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(2592000 * rate(prometheus_tsdb_head_samples_appended_total[1h]) * (rate(prometheus_tsdb_compaction_chunk_size_bytes_sum[1d]) / rate(prometheus_tsdb_compaction_chunk_samples_sum[1d])))/1073741824"
    }
   ]
  },
  {
   "title": "Rule Evaluation Failures / 30m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_rule_evaluation_failures_total[30m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "<img src=\"http://prometheus.io/assets/prometheus_logo_grey.svg\" alt=\"Prometheus logo\" style=\"height: 40px;\">\n<span style=\"font-family: 'Open Sans', 'Helvetica Neue', Helvetica; font-size: 25px;vertical-align: text-top;color: #bbbfc2;margin-left: 10px;\">Prometheus</span>\n\n<p style=\"margin-top: 10px;\">You're using Prometheus, an open-source systems monitoring and alerting toolkit originally built at SoundCloud. For more information, check out the <a href=\"http://www.grafana.org/\">Grafana</a> and <a href=\"http://prometheus.io/\">Prometheus</a> projects.</p>"
   },
   "content": "<img src=\"http://prometheus.io/assets/prometheus_logo_grey.svg\" alt=\"Prometheus logo\" style=\"height: 40px;\">\n<span style=\"font-family: 'Open Sans', 'Helvetica Neue', Helvetica; font-size: 25px;vertical-align: text-top;color: #bbbfc2;margin-left: 10px;\">Prometheus</span>\n\n<p style=\"margin-top: 10px;\">You're using Prometheus, an open-source systems monitoring and alerting toolkit originally built at SoundCloud. For more information, check out the <a href=\"http://www.grafana.org/\">Grafana</a> and <a href=\"http://prometheus.io/\">Prometheus</a> projects.</p>"
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 5 },
   "options": {
    "content": "#### Samples Ingested\nThis graph displays the count of samples ingested by the Prometheus server, as measured over the last 5 minutes, per time series in the range vector. When troubleshooting an issue on IRC or Github, this is often the first stat requested by the Prometheus team. "
   },
   "content": "#### Samples Ingested\nThis graph displays the count of samples ingested by the Prometheus server, as measured over the last 5 minutes, per time series in the range vector. When troubleshooting an issue on IRC or Github, this is often the first stat requested by the Prometheus team. "
  },
  {
   "title": "Samples ingested (rate-5m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_samples_in_total[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "options": {
    "content": "#### Scrapes\nPrometheus scrapes metrics from instrumented jobs, either directly or via an intermediary push gateway for short-lived jobs. Target scrapes will show how frequently targets are scraped, as measured over the last 5 minutes, per time series in the range vector. Scrape Duration will show how long the scrapes are taking, with percentiles available as series. "
   },
   "content": "#### Scrapes\nPrometheus scrapes metrics from instrumented jobs, either directly or via an intermediary push gateway for short-lived jobs. Target scrapes will show how frequently targets are scraped, as measured over the last 5 minutes, per time series in the range vector. Scrape Duration will show how long the scrapes are taking, with percentiles available as series. "
  },
  {
   "title": "Target Scrapes (last 5m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_count[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{quantile!=\"0.01\", quantile!=\"0.05\"}",
     "legendFormat": "{{quantile}} ({{interval}})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "options": {
    "content": "#### Rule Evaluation Duration\nThis graph panel plots the duration for all evaluations to execute. The 50th percentile, 90th percentile and 99th percentile are shown as three separate series to help identify outliers that may be skewing the data."
   },
   "content": "#### Rule Evaluation Duration\nThis graph panel plots the duration for all evaluations to execute. The 50th percentile, 90th percentile and 99th percentile are shown as three separate series to help identify outliers that may be skewing the data."
  },
  {
   "title": "Rule Eval Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "prometheus_rule_evaluation_duration_seconds{quantile!=\"0.01\", quantile!=\"0.05\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}